### ISSUE TITLE
Authentication fails under Python3

### ISSUE THREAD

**Issue by ExTechOp** [rambo/python-holviapi#17]
The following code (with the appropriate tokens in the Connection call) works under Python 2.7.13 but fails with "401 Client Error: UNAUTHORIZED" under Python 3.5.2
```
import holviapi
cnc = holviapi.Connection("XXXXXX","YYYYYYYYYYYYYYYYY")
ia = holviapi.InvoiceAPI(cnc)
invoice_list = holviapi.InvoiceAPI.list_invoices(ia)
```
The authentication error message under Python3 is:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/holviapi/connection.py", line 55, in make_get
    r.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://holvi.com/api/pool/XXXXXX/invoice/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./minimal_read.py", line 12, in <module>
    invoice_list = holviapi.InvoiceAPI.list_invoices(ia)
  File "/usr/lib/python3.5/site-packages/holviapi/invoicing.py", line 210, in list_invoices
    invoices = self.connection.make_get(self.base_url, params=kwargs)
  File "/usr/lib/python3.5/site-packages/holviapi/connection.py", line 60, in make_get
    raise AuthenticationError(e.__str__(), response=e.response)  # six.u messes this up
holviapi.errors.AuthenticationError: 401 Client Error: UNAUTHORIZED for url: https://holvi.com/api/pool/XXXXXX/invoice/ Details: {'detail': 'Invalid token'}
```

**Comment by rambo** [comment]
You need to use the `ia` instance bound method for `list_invoices`

    import holviapi
    cnc = holviapi.Connection('CENCOR','CENCOR')
    ia = holviapi.InvoiceAPI(cnc)
    l = ia.list_invoices()
    i = next(l)

**Comment by ExTechOp** [comment]
Indeed, the code is now
```
import holviapi
cnc = holviapi.Connection("XXXXXX","YYYYYYYYYYYYYYYYY")
ia = holviapi.InvoiceAPI(cnc)
invoice_list = ia.list_invoices()
```
And this consistently fails with Fedora 25 and python3-3.5.2-4.fc25.x86_64 package. Another question is if there's something wrong in the http connection packages etc. delivered with the system, I'm too much of a Python newbie to figure this out on my own.

**Comment by rambo** [comment]
For some reason I was thinking of the six unicode error you posted elsewhere earlier, this authentication error is exactly that, `{'detail': 'Invalid token'}` is the response from Holvis side.

either your pool or your apikey is wrong.

**Comment by ExTechOp** [comment]
Nope, I can just change the first line of the file to read either of the following and it'll work with the 1st one but fail giving the authentication error with the 2nd one
```
#!/usr/bin/python
#!/usr/bin/python3
```

**Comment by rambo** [comment]
Can't reproduce the auth issue, did reproduce the `six.u` issue. anyway correct shebang is
`#!/usr/bin/env python3`

**Comment by ExTechOp** [comment]
Yeah, I know that pythonites want to do everything Their Way™, but the "classic" shebang with the full path does exactly the same thing if you aren't giving env any options or name=value pairs.
